# Github actions workflow definition.
name: Test the localgov_menu_link_group Drupal module.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Clone drupal_container
        uses: actions/checkout@v2
        with:
          repository: localgovdrupal/drupal-container
          ref: master

      - name: Create LocalGov Drupal project
        run: composer create-project --stability dev localgovdrupal/localgov-project html

      - name: Checkout localgov_menu_link_group repo to test
        uses: actions/checkout@v2
        with:
          path: html/web/modules/contrib/localgov_menu_link_group

      - name: Start Docker environment
        run: docker-compose up -d

      - name: Run tests
        run: ./run-tests.sh
        shell: bash
